#!/usr/bin/env python3
import cv2
import numpy as np
import os
import glob
from typing import Optional, Tuple

# ==========================================
# CONFIGURATION
# ==========================================
# Fill these out with the paths to your datasets
PFIB_INPUT_DIR = "/home/lys/projects/POC_Dataset/for_ControlNet_defect/target"
AVALON_INPUT_DIR = "/home/lys/projects/POC_Dataset/for_ControlNet_defect/source"
GT_MASK_DIR = "/home/lys/projects/POC_Dadaset/20251208/patches/gt"  # Optional: Path to ground truth defect masks. If empty, the script attempts naive extraction.
PIX2PIX_DIR = "/home/lys/projects/POC_Dataset/for_ControlNet_defect/source_defect_avalon"  # Required if using pix2pix grafting: Path to defective Avalon images generated by Pix2Pix
OUTPUT_DIR = "/home/lys/projects/POC_Dataset/for_ControlNet_defect/generated_defect_avalon_140426"
EDGEMAP_OUTPUT_DIR = "/home/lys/projects/POC_Dataset/for_ControlNet_defect/generated_edges_140426"  # Optional: Path to save the extracted edge maps of the generated defect avalon

# ==========================================
# PIPELINE FUNCTIONS
# ==========================================


def align_images(pfib_img: np.ndarray, avalon_img: np.ndarray) -> np.ndarray:
    """
    Step 1: Alignment
    Aligns the PFIB image to the Avalon image using phase correlation or ECC.
    """
    # Convert to grayscale for alignment
    pfib_gray = (
        cv2.cvtColor(pfib_img, cv2.COLOR_BGR2GRAY)
        if len(pfib_img.shape) == 3
        else pfib_img
    )
    avalon_gray = (
        cv2.cvtColor(avalon_img, cv2.COLOR_BGR2GRAY)
        if len(avalon_img.shape) == 3
        else avalon_img
    )

    # Ensure images are the same size for phaseCorrelate
    if pfib_gray.shape != avalon_gray.shape:
        pfib_gray = cv2.resize(pfib_gray, (avalon_gray.shape[1], avalon_gray.shape[0]))
        pfib_img = cv2.resize(pfib_img, (avalon_img.shape[1], avalon_img.shape[0]))

    # Convert to float32 for phaseCorrelate
    pfib_f32 = pfib_gray.astype(np.float32)
    avalon_f32 = avalon_gray.astype(np.float32)

    # Calculate phase correlation to find translation shift
    shift, _ = cv2.phaseCorrelate(pfib_f32, avalon_f32)

    # Create translation matrix
    tx, ty = shift
    M = np.array([[1, 0, tx], [0, 1, ty]], dtype=np.float32)

    # Warp the original PFIB image
    aligned_pfib = cv2.warpAffine(
        pfib_img, M, (avalon_img.shape[1], avalon_img.shape[0])
    )

    return aligned_pfib


def extract_defects(aligned_pfib: np.ndarray, avalon_img: np.ndarray) -> np.ndarray:
    """
    Step 2: Defect Extraction
    Extracts defects by finding the absolute difference and applying adaptive thresholding.
    """
    pfib_gray = (
        cv2.cvtColor(aligned_pfib, cv2.COLOR_BGR2GRAY)
        if len(aligned_pfib.shape) == 3
        else aligned_pfib
    )
    avalon_gray = (
        cv2.cvtColor(avalon_img, cv2.COLOR_BGR2GRAY)
        if len(avalon_img.shape) == 3
        else avalon_img
    )

    # Calculate absolute difference
    diff = cv2.absdiff(pfib_gray, avalon_gray)

    # Apply adaptive thresholding to isolate defects
    # Using a simple binary threshold here, but adaptiveThreshold can also be used
    _, thresh = cv2.threshold(diff, 30, 255, cv2.THRESH_BINARY)

    # Morphological operations to clean up noise
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5, 5))
    cleaned_mask = cv2.morphologyEx(thresh, cv2.MORPH_OPEN, kernel)
    cleaned_mask = cv2.morphologyEx(cleaned_mask, cv2.MORPH_CLOSE, kernel)

    return cleaned_mask


def cadify_defects(defect_mask: np.ndarray) -> np.ndarray:
    """
    Step 3: CAD-ification
    Simplifies the organic defect shapes into CAD-like polygons using findContours and approxPolyDP.
    """
    # Find contours of the defects
    contours, _ = cv2.findContours(
        defect_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE
    )

    # Create an empty mask for the CAD-ified defects
    cad_mask = np.zeros_like(defect_mask)

    for contour in contours:
        # Filter out very small noise contours
        if cv2.contourArea(contour) > 20:
            # Approximate the contour to a polygon
            epsilon = 0.02 * cv2.arcLength(contour, True)
            approx = cv2.approxPolyDP(contour, epsilon, True)

            # Draw the approximated polygon onto the mask
            cv2.drawContours(cad_mask, [approx], -1, 255, thickness=cv2.FILLED)

    return cad_mask


def composite_defects(avalon_img: np.ndarray, cad_mask: np.ndarray) -> np.ndarray:
    """
    Step 4: Compositing
    Overlays the CAD-ified defects onto the Avalon image.
    """
    if len(cad_mask.shape) == 2:
        mask_3ch = cv2.cvtColor(cad_mask, cv2.COLOR_GRAY2BGR)
    else:
        mask_3ch = cad_mask

    return cv2.bitwise_or(avalon_img, mask_3ch)


def composite_pix2pix_defects(
    clean_avalon_img: np.ndarray, pix2pix_img: np.ndarray, defect_mask: np.ndarray
) -> np.ndarray:
    """
    Step 4: Compositing (Pix2Pix approach)
    Uses the ground truth defect mask to copy the generated defect area from the pix2pix image
    and paste it directly onto the clean Avalon image.
    """
    # Ensure the mask has 3 channels to match the images
    if len(defect_mask.shape) == 2:
        mask_3ch = cv2.cvtColor(defect_mask, cv2.COLOR_GRAY2BGR)
    else:
        mask_3ch = defect_mask

    # Normalize mask to 0-1 for blending
    mask_normalized = mask_3ch.astype(float) / 255.0

    # Ensure images are float for blending
    clean_f = clean_avalon_img.astype(float)
    pix2pix_f = pix2pix_img.astype(float)

    # Composite: (Pix2Pix * Mask) + (Clean * (1 - Mask))
    # Where mask is 1 (defect), use pix2pix. Where mask is 0 (normal), use clean avalon.
    composited_f = (pix2pix_f * mask_normalized) + (clean_f * (1.0 - mask_normalized))

    return composited_f.astype(np.uint8)


# ==========================================
# MAIN EXECUTION
# ==========================================


def main():
    print("Starting Semantic Defect Grafting Pipeline...")

    if not PFIB_INPUT_DIR or not AVALON_INPUT_DIR or not OUTPUT_DIR:
        print("Error: Input/Output directories are not set.")
        print(
            "Please open pipeline.py and set PFIB_INPUT_DIR, AVALON_INPUT_DIR, and OUTPUT_DIR."
        )
        return

    # Ensure output directory exists
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    if EDGEMAP_OUTPUT_DIR:
        os.makedirs(EDGEMAP_OUTPUT_DIR, exist_ok=True)

    # Find all images in the PFIB directory
    pfib_files = glob.glob(os.path.join(PFIB_INPUT_DIR, "*.*"))

    if not pfib_files:
        print(f"No files found in {PFIB_INPUT_DIR}")
        return

    for pfib_path in pfib_files:
        filename = os.path.basename(pfib_path)
        avalon_path = os.path.join(AVALON_INPUT_DIR, filename)

        if not os.path.exists(avalon_path):
            print(f"Warning: Matching Avalon image not found for {filename}. Skipping.")
            continue

        print(f"Processing {filename}...")

        # Load images
        pfib_img = cv2.imread(pfib_path)
        avalon_img = cv2.imread(avalon_path)

        if pfib_img is None or avalon_img is None:
            print(f"Error loading images for {filename}. Skipping.")
            continue

        # Check for Pix2Pix image if we are doing grafting
        pix2pix_img = None
        if PIX2PIX_DIR:
            pix2pix_path = os.path.join(PIX2PIX_DIR, filename)
            pix2pix_img = cv2.imread(pix2pix_path)
            if pix2pix_img is None:
                print(f"Error loading Pix2Pix image for {filename}. Skipping.")
                continue

        # Step 1: Alignment (Bypassed since images are already aligned)
        # aligned_pfib = align_images(pfib_img, avalon_img)
        aligned_pfib = pfib_img

        # Step 2: Defect Extraction
        if GT_MASK_DIR:
            mask_path = os.path.join(GT_MASK_DIR, filename)
            if not os.path.exists(mask_path):
                print(
                    f"Warning: Ground truth mask not found for {filename} in {GT_MASK_DIR}. Skipping."
                )
                continue
            # Read the ground truth mask in grayscale
            gt_mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)
            if gt_mask is None:
                print(f"Error loading mask for {filename}. Skipping.")
                continue
            # Ensure binary (0 or 255)
            _, defect_mask = cv2.threshold(gt_mask, 127, 255, cv2.THRESH_BINARY)
        else:
            # Fallback to naive unsupervised extraction (warning: prone to errors due to domain gap)
            defect_mask = extract_defects(aligned_pfib, avalon_img)

        # Step 3 & 4: Pix2Pix Compositing OR CAD-ification
        if PIX2PIX_DIR and pix2pix_img is not None:
            # If Pix2Pix is provided, we skip CAD-ification and just paste the Pix2Pix texture
            # over the clean Avalon using the defect mask
            final_img = composite_pix2pix_defects(avalon_img, pix2pix_img, defect_mask)
        else:
            # Old flow: Create fake CAD polygons
            cad_mask = cadify_defects(defect_mask)
            final_img = composite_defects(avalon_img, cad_mask)

        # Save the result
        output_path = os.path.join(OUTPUT_DIR, filename)
        cv2.imwrite(output_path, final_img)

        # Generate and save edge map if directory is provided
        if EDGEMAP_OUTPUT_DIR:
            # Using Canny edge detection (standard for ControlNet datasets)
            edges = cv2.Canny(final_img, 100, 200)
            edge_output_path = os.path.join(EDGEMAP_OUTPUT_DIR, filename)
            cv2.imwrite(edge_output_path, edges)

    print(f"Pipeline complete. Results saved to {OUTPUT_DIR}")
    if EDGEMAP_OUTPUT_DIR:
        print(f"Edge maps saved to {EDGEMAP_OUTPUT_DIR}")


if __name__ == "__main__":
    main()
